"""OpenAPI schema and TypeScript client generation utilities.

Extracts the OpenAPI schema from a FastAPI application and optionally
generates a lightweight TypeScript client.

Usage::

    from ml_platform.serving.openapi_export import (
        export_openapi_schema,
        generate_typescript_types,
    )

    app = create_stateful_app(MyService, config)
    schema = export_openapi_schema(app)
    ts_types = generate_typescript_types(schema)
"""

from __future__ import annotations

import json
import logging
from typing import Any

logger = logging.getLogger(__name__)

__all__ = [
    "export_openapi_schema",
    "generate_typescript_types",
    "generate_typescript_client",
]


def export_openapi_schema(app: Any, *, output_path: str = "") -> dict[str, Any]:
    """Extract the OpenAPI schema from a FastAPI application.

    Args:
        app: A FastAPI application instance.
        output_path: Optional file path to write the schema JSON.

    Returns:
        OpenAPI schema as a dict.
    """
    schema = app.openapi()
    if output_path:
        with open(output_path, "w") as f:
            json.dump(schema, f, indent=2)
        logger.info("Wrote OpenAPI schema to %s", output_path)
    return schema


def generate_typescript_types(schema: dict[str, Any]) -> str:
    """Generate TypeScript type definitions from an OpenAPI schema.

    Produces a ``types.ts`` file with interfaces for all request/response
    schemas defined in the OpenAPI document.

    Args:
        schema: OpenAPI schema dict (as returned by :func:`export_openapi_schema`).

    Returns:
        TypeScript source code string.
    """
    lines: list[str] = [
        "// Auto-generated by ml-platform from OpenAPI schema",
        f"// API: {schema.get('info', {}).get('title', 'Unknown')} v{schema.get('info', {}).get('version', '0')}",
        "",
    ]

    components = schema.get("components", {}).get("schemas", {})
    for name, defn in sorted(components.items()):
        lines.append(f"export interface {name} {{")
        properties = defn.get("properties", {})
        required = set(defn.get("required", []))
        for prop_name, prop_def in sorted(properties.items()):
            ts_type = _openapi_type_to_ts(prop_def)
            optional = "" if prop_name in required else "?"
            lines.append(f"  {prop_name}{optional}: {ts_type};")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def generate_typescript_client(schema: dict[str, Any], *, base_url: str = "") -> str:
    """Generate a lightweight TypeScript API client from an OpenAPI schema.

    Args:
        schema: OpenAPI schema dict.
        base_url: Default base URL for the API client.

    Returns:
        TypeScript source code string for the client.
    """
    lines: list[str] = [
        "// Auto-generated API client by ml-platform",
        f"// API: {schema.get('info', {}).get('title', 'Unknown')}",
        "",
        "export class APIClient {",
        "  private baseUrl: string;",
        "  private headers: Record<string, string>;",
        "",
        f'  constructor(baseUrl: string = "{base_url}", headers: Record<string, string> = {{}}) {{',
        "    this.baseUrl = baseUrl;",
        "    this.headers = { 'Content-Type': 'application/json', ...headers };",
        "  }",
        "",
        "  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {",
        "    const resp = await fetch(`${this.baseUrl}${path}`, {",
        "      method,",
        "      headers: this.headers,",
        "      body: body ? JSON.stringify(body) : undefined,",
        "    });",
        "    if (!resp.ok) throw new Error(`HTTP ${resp.status}: ${resp.statusText}`);",
        "    return resp.json();",
        "  }",
        "",
    ]

    paths = schema.get("paths", {})
    for path, methods in sorted(paths.items()):
        for method, operation in sorted(methods.items()):
            if method in ("parameters", "servers"):
                continue
            op_id = operation.get("operationId", f"{method}_{path.replace('/', '_')}")
            fn_name = _to_camel_case(op_id)
            summary = operation.get("summary", "")

            has_body = method in ("post", "put", "patch")
            params = "body?: unknown" if has_body else ""
            body_arg = "body" if has_body else "undefined"

            if summary:
                lines.append(f"  /** {summary} */")
            lines.append(f"  async {fn_name}({params}): Promise<unknown> {{")
            lines.append(f'    return this.request("{method.upper()}", "{path}", {body_arg});')
            lines.append("  }")
            lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _openapi_type_to_ts(prop: dict[str, Any]) -> str:
    """Convert an OpenAPI type definition to a TypeScript type."""
    if "$ref" in prop:
        ref = prop["$ref"]
        return ref.rsplit("/", 1)[-1]

    any_of = prop.get("anyOf", [])
    if any_of:
        types = [_openapi_type_to_ts(t) for t in any_of if t.get("type") != "null"]
        null = any(t.get("type") == "null" for t in any_of)
        ts = " | ".join(types) if types else "unknown"
        return f"{ts} | null" if null else ts

    oa_type = prop.get("type", "")
    if oa_type == "string":
        return "string"
    if oa_type == "integer" or oa_type == "number":
        return "number"
    if oa_type == "boolean":
        return "boolean"
    if oa_type == "array":
        items = prop.get("items", {})
        return f"Array<{_openapi_type_to_ts(items)}>"
    if oa_type == "object":
        return "Record<string, unknown>"
    return "unknown"


def _to_camel_case(name: str) -> str:
    """Convert snake_case or kebab-case to camelCase."""
    parts = name.replace("-", "_").split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])
