"""CloudWatch monitoring construct for ML platform services.

Creates CloudWatch alarms targeting key ML operational metrics, an SNS
topic for notifications, and optionally a CloudWatch dashboard whose
layout is generated by :pyfunc:`ml_platform.monitoring.dashboards.generate_cloudwatch_dashboard`.

Usage::

    from ml_platform.infra.constructs import MonitoringConstruct

    mon = MonitoringConstruct(
        self, "Monitoring",
        service_name="inference-api",
        alarm_email="oncall@example.com",
    )
"""

from __future__ import annotations

from aws_cdk import (
    CfnOutput,
    Duration,
    aws_cloudwatch as cw,
    aws_cloudwatch_actions as cw_actions,
    aws_sns as sns,
    aws_sns_subscriptions as subs,
)
from constructs import Construct

from ml_platform.monitoring.dashboards import generate_cloudwatch_dashboard


class MonitoringConstruct(Construct):
    """CloudWatch alarms, SNS topic, and optional dashboard for an ML service.

    Alarms created:

    * **RewardDrop** — fires when ``cumulative_reward`` falls below a
      threshold, indicating the bandit/model is under-performing.
    * **BudgetOvershoot** — fires when ``pacer_cost_ema`` exceeds the
      budget ceiling, meaning the service is spending too aggressively.
    * **HighLatency** — fires when ``latency_ms`` P95 exceeds the
      latency SLO.
    * **ExplorationCollapse** — fires when ``exploration_rate`` drops
      near zero, signalling the policy has stopped exploring.

    When ``create_dashboard=True`` the construct deploys a CloudWatch
    dashboard using the widget definitions from
    :pyfunc:`ml_platform.monitoring.dashboards.generate_cloudwatch_dashboard`.

    Args:
        scope: CDK construct scope.
        construct_id: Logical ID within the construct tree.
        service_name: Service name matching the ``service`` CloudWatch
            dimension emitted by :pyclass:`ml_platform.monitoring.MetricsEmitter`.
        alarm_email: Optional e-mail address.  When provided, an SNS
            e-mail subscription is created so alarm state changes trigger
            notifications.
        namespace: CloudWatch metrics namespace.
        create_dashboard: Whether to create a CloudWatch dashboard.
        reward_drop_threshold: Alarm threshold for cumulative reward.
        budget_overshoot_threshold: Alarm threshold for cost EMA.
        latency_p95_threshold_ms: Alarm threshold for P95 latency in ms.
        exploration_collapse_threshold: Alarm threshold for exploration rate.
        evaluation_periods: Number of consecutive periods a metric must
            breach before the alarm fires.
        period: Evaluation period for alarms.
        region: AWS region passed to the dashboard generator.
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        service_name: str,
        alarm_email: str | None = None,
        namespace: str = "MLPlatform",
        create_dashboard: bool = True,
        reward_drop_threshold: float = 0.0,
        budget_overshoot_threshold: float = 1.0,
        latency_p95_threshold_ms: float = 500.0,
        exploration_collapse_threshold: float = 0.01,
        evaluation_periods: int = 3,
        period: Duration = Duration.minutes(5),
        region: str | None = None,
    ) -> None:
        super().__init__(scope, construct_id)

        topic = sns.Topic(
            self,
            "AlarmTopic",
            display_name=f"{service_name} ML Alarms",
            topic_name=f"{service_name}-ml-alarms",
        )

        if alarm_email:
            topic.add_subscription(subs.EmailSubscription(alarm_email))

        self._alarm_topic = topic

        alarm_action = cw_actions.SnsAction(topic)

        def _metric(metric_name: str, statistic: str = "Average") -> cw.Metric:
            return cw.Metric(
                namespace=namespace,
                metric_name=metric_name,
                dimensions_map={"service": service_name},
                statistic=statistic,
                period=period,
            )

        reward_alarm = cw.Alarm(
            self,
            "RewardDropAlarm",
            alarm_name=f"{service_name}-reward-drop",
            alarm_description=(
                "Cumulative reward has fallen below the acceptable threshold, "
                "indicating degraded model performance."
            ),
            metric=_metric("cumulative_reward", "Maximum"),
            threshold=reward_drop_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.LESS_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.BREACHING,
        )
        reward_alarm.add_alarm_action(alarm_action)

        budget_alarm = cw.Alarm(
            self,
            "BudgetOvershootAlarm",
            alarm_name=f"{service_name}-budget-overshoot",
            alarm_description=(
                "Cost EMA has exceeded the budget ceiling, indicating the "
                "service is spending too aggressively."
            ),
            metric=_metric("pacer_cost_ema"),
            threshold=budget_overshoot_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        budget_alarm.add_alarm_action(alarm_action)

        latency_alarm = cw.Alarm(
            self,
            "HighLatencyAlarm",
            alarm_name=f"{service_name}-high-latency",
            alarm_description=(
                "P95 prediction latency has exceeded the SLO threshold."
            ),
            metric=_metric("latency_ms", "p95"),
            threshold=latency_p95_threshold_ms,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        latency_alarm.add_alarm_action(alarm_action)

        exploration_alarm = cw.Alarm(
            self,
            "ExplorationCollapseAlarm",
            alarm_name=f"{service_name}-exploration-collapse",
            alarm_description=(
                "Exploration rate has dropped near zero — the policy has "
                "stopped exploring and may be stuck on a suboptimal arm."
            ),
            metric=_metric("exploration_rate"),
            threshold=exploration_collapse_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.LESS_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.BREACHING,
        )
        exploration_alarm.add_alarm_action(alarm_action)

        if create_dashboard:
            dashboard_body = generate_cloudwatch_dashboard(
                service_name=service_name,
                region=region,
                namespace=namespace,
            )
            cw.CfnDashboard(
                self,
                "Dashboard",
                dashboard_name=f"{service_name}-ml-dashboard",
                dashboard_body=dashboard_body,
            )

        CfnOutput(
            self,
            "AlarmTopicArn",
            value=topic.topic_arn,
            description=f"SNS topic ARN for {service_name} alarms",
            export_name=f"{service_name}-alarm-topic-arn",
        )

    @property
    def alarm_topic(self) -> sns.ITopic:
        """SNS topic to which all alarm state-change notifications are sent."""
        return self._alarm_topic
