"""CloudWatch monitoring construct for ML platform services.

Creates CloudWatch alarms targeting key operational metrics, an SNS
topic for notifications, and optionally a CloudWatch dashboard whose
layout is generated by :pyfunc:`ml_platform.monitoring.dashboards.generate_cloudwatch_dashboard`.

Supports two alarm profiles:

* **ML alarms** (default) — reward drop, budget overshoot, high latency,
  and exploration collapse.  Suitable for bandit/RL services.
* **Web service alarms** — ALB 5xx errors, target response time,
  unhealthy targets, ECS running task count, and RDS CPU / storage /
  connections.  Activated by passing ``alb``, ``ecs_service``, or
  ``rds_instance``.

Usage — ML service::

    mon = MonitoringConstruct(
        self, "Monitoring",
        service_name="inference-api",
        alarm_email="oncall@example.com",
    )

Usage — web service::

    mon = MonitoringConstruct(
        self, "Monitoring",
        service_name="my-web-app",
        alarm_email="oncall@example.com",
        alb=ecs_service.service.load_balancer,
        ecs_service=ecs_service.service.service,
        rds_instance=database,
        include_ml_alarms=False,
    )
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from aws_cdk import (
    CfnOutput,
    Duration,
    aws_cloudwatch as cw,
    aws_cloudwatch_actions as cw_actions,
    aws_sns as sns,
    aws_sns_subscriptions as subs,
)
from constructs import Construct

from ml_platform.monitoring.dashboards import generate_cloudwatch_dashboard

if TYPE_CHECKING:
    from aws_cdk import (
        aws_ecs as ecs,
        aws_elasticloadbalancingv2 as elbv2,
        aws_rds as rds,
    )


class MonitoringConstruct(Construct):
    """CloudWatch alarms, SNS topic, and optional dashboard.

    Args:
        scope: CDK construct scope.
        construct_id: Logical ID within the construct tree.
        service_name: Service name used for alarm names, SNS topic,
            dashboard title, and the ``service`` CloudWatch dimension
            emitted by :pyclass:`ml_platform.monitoring.MetricsEmitter`.
        alarm_email: Optional e-mail address.  When provided, an SNS
            e-mail subscription is created so alarm state changes trigger
            notifications.
        namespace: CloudWatch metrics namespace for ML alarms.
        create_dashboard: Whether to create a CloudWatch dashboard.
        include_ml_alarms: When ``True`` (default), create the four
            ML-specific alarms (reward, budget, latency, exploration).
            Set to ``False`` for web-only services.
        alb: Optional ALB reference.  When provided, creates ALB 5xx,
            response time, and unhealthy-target alarms.
        ecs_service: Optional ECS Fargate service.  When provided,
            creates a running-task-count alarm.
        rds_instance: Optional RDS database instance.  When provided,
            creates CPU, free-storage, and connection-count alarms.
        alb_5xx_threshold: Per-period 5xx count that triggers the alarm.
        alb_response_time_threshold: P95 target response time in seconds.
        ecs_min_healthy_tasks: Alarm fires when running tasks drop below
            this value.
        rds_cpu_threshold: Alarm fires when CPU utilisation exceeds this
            percentage.
        rds_free_storage_threshold_bytes: Alarm fires when free storage
            falls below this value in bytes (default 1 GB).
        rds_connections_threshold: Alarm fires when active connections
            exceed this value.
        reward_drop_threshold: (ML) Alarm threshold for cumulative reward.
        budget_overshoot_threshold: (ML) Alarm threshold for cost EMA.
        latency_p95_threshold_ms: (ML) Alarm threshold for P95 latency.
        exploration_collapse_threshold: (ML) Alarm threshold for
            exploration rate.
        evaluation_periods: Number of consecutive periods a metric must
            breach before the alarm fires.
        period: Evaluation period for alarms.
        region: AWS region passed to the dashboard generator.
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        service_name: str,
        alarm_email: str | None = None,
        namespace: str = "MLPlatform",
        create_dashboard: bool = True,
        include_ml_alarms: bool = True,
        # Web service resource references
        alb: elbv2.IApplicationLoadBalancer | None = None,
        ecs_service: ecs.FargateService | None = None,
        rds_instance: rds.IDatabaseInstance | None = None,
        # Web alarm thresholds
        alb_5xx_threshold: int = 10,
        alb_response_time_threshold: float = 5.0,
        ecs_min_healthy_tasks: int = 1,
        rds_cpu_threshold: float = 80.0,
        rds_free_storage_threshold_bytes: int = 1_000_000_000,
        rds_connections_threshold: int = 50,
        # ML alarm thresholds
        reward_drop_threshold: float = 0.0,
        budget_overshoot_threshold: float = 1.0,
        latency_p95_threshold_ms: float = 500.0,
        exploration_collapse_threshold: float = 0.01,
        # Shared
        evaluation_periods: int = 3,
        period: Duration = Duration.minutes(5),
        region: str | None = None,
    ) -> None:
        super().__init__(scope, construct_id)

        topic = sns.Topic(
            self,
            "AlarmTopic",
            display_name=f"{service_name} Alarms",
            topic_name=f"{service_name}-alarms",
        )

        if alarm_email:
            topic.add_subscription(subs.EmailSubscription(alarm_email))

        self._alarm_topic = topic
        self._alarms: list[cw.Alarm] = []

        alarm_action = cw_actions.SnsAction(topic)

        # -- ML alarms (opt-in) ------------------------------------------------

        if include_ml_alarms:
            self._create_ml_alarms(
                service_name=service_name,
                namespace=namespace,
                alarm_action=alarm_action,
                evaluation_periods=evaluation_periods,
                period=period,
                reward_drop_threshold=reward_drop_threshold,
                budget_overshoot_threshold=budget_overshoot_threshold,
                latency_p95_threshold_ms=latency_p95_threshold_ms,
                exploration_collapse_threshold=exploration_collapse_threshold,
            )

        # -- Web service alarms (opt-in via resource references) ---------------

        if alb is not None:
            self._create_alb_alarms(
                service_name=service_name,
                alb=alb,
                alarm_action=alarm_action,
                evaluation_periods=evaluation_periods,
                period=period,
                error_5xx_threshold=alb_5xx_threshold,
                response_time_threshold=alb_response_time_threshold,
            )

        if ecs_service is not None:
            self._create_ecs_alarms(
                service_name=service_name,
                ecs_service=ecs_service,
                alarm_action=alarm_action,
                evaluation_periods=evaluation_periods,
                period=period,
                min_healthy_tasks=ecs_min_healthy_tasks,
            )

        if rds_instance is not None:
            self._create_rds_alarms(
                service_name=service_name,
                rds_instance=rds_instance,
                alarm_action=alarm_action,
                evaluation_periods=evaluation_periods,
                period=period,
                cpu_threshold=rds_cpu_threshold,
                free_storage_threshold_bytes=rds_free_storage_threshold_bytes,
                connections_threshold=rds_connections_threshold,
            )

        # -- Dashboard ---------------------------------------------------------

        if create_dashboard:
            dashboard_body = generate_cloudwatch_dashboard(
                service_name=service_name,
                region=region,
                namespace=namespace,
            )
            dashboard_suffix = "dashboard" if not include_ml_alarms else "ml-dashboard"
            cw.CfnDashboard(
                self,
                "Dashboard",
                dashboard_name=f"{service_name}-{dashboard_suffix}",
                dashboard_body=dashboard_body,
            )

        CfnOutput(
            self,
            "AlarmTopicArn",
            value=topic.topic_arn,
            description=f"SNS topic ARN for {service_name} alarms",
            export_name=f"{service_name}-alarm-topic-arn",
        )

    # -- Properties ------------------------------------------------------------

    @property
    def alarm_topic(self) -> sns.ITopic:
        """SNS topic to which all alarm state-change notifications are sent."""
        return self._alarm_topic

    @property
    def alarms(self) -> list[cw.Alarm]:
        """All CloudWatch alarms created by this construct."""
        return list(self._alarms)

    # -- ML alarms -------------------------------------------------------------

    def _create_ml_alarms(
        self,
        *,
        service_name: str,
        namespace: str,
        alarm_action: cw_actions.SnsAction,
        evaluation_periods: int,
        period: Duration,
        reward_drop_threshold: float,
        budget_overshoot_threshold: float,
        latency_p95_threshold_ms: float,
        exploration_collapse_threshold: float,
    ) -> None:
        def _metric(metric_name: str, statistic: str = "Average") -> cw.Metric:
            return cw.Metric(
                namespace=namespace,
                metric_name=metric_name,
                dimensions_map={"service": service_name},
                statistic=statistic,
                period=period,
            )

        reward_alarm = cw.Alarm(
            self,
            "RewardDropAlarm",
            alarm_name=f"{service_name}-reward-drop",
            alarm_description=(
                "Cumulative reward has fallen below the acceptable threshold, "
                "indicating degraded model performance."
            ),
            metric=_metric("cumulative_reward", "Maximum"),
            threshold=reward_drop_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.LESS_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.BREACHING,
        )
        reward_alarm.add_alarm_action(alarm_action)
        self._alarms.append(reward_alarm)

        budget_alarm = cw.Alarm(
            self,
            "BudgetOvershootAlarm",
            alarm_name=f"{service_name}-budget-overshoot",
            alarm_description=(
                "Cost EMA has exceeded the budget ceiling, indicating the "
                "service is spending too aggressively."
            ),
            metric=_metric("pacer_cost_ema"),
            threshold=budget_overshoot_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        budget_alarm.add_alarm_action(alarm_action)
        self._alarms.append(budget_alarm)

        latency_alarm = cw.Alarm(
            self,
            "HighLatencyAlarm",
            alarm_name=f"{service_name}-high-latency",
            alarm_description=(
                "P95 prediction latency has exceeded the SLO threshold."
            ),
            metric=_metric("latency_ms", "p95"),
            threshold=latency_p95_threshold_ms,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        latency_alarm.add_alarm_action(alarm_action)
        self._alarms.append(latency_alarm)

        exploration_alarm = cw.Alarm(
            self,
            "ExplorationCollapseAlarm",
            alarm_name=f"{service_name}-exploration-collapse",
            alarm_description=(
                "Exploration rate has dropped near zero — the policy has "
                "stopped exploring and may be stuck on a suboptimal arm."
            ),
            metric=_metric("exploration_rate"),
            threshold=exploration_collapse_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.LESS_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.BREACHING,
        )
        exploration_alarm.add_alarm_action(alarm_action)
        self._alarms.append(exploration_alarm)

    # -- ALB alarms ------------------------------------------------------------

    def _create_alb_alarms(
        self,
        *,
        service_name: str,
        alb: elbv2.IApplicationLoadBalancer,
        alarm_action: cw_actions.SnsAction,
        evaluation_periods: int,
        period: Duration,
        error_5xx_threshold: int,
        response_time_threshold: float,
    ) -> None:
        alb_full_name = alb.load_balancer_full_name

        alb_5xx = cw.Alarm(
            self,
            "ALB5xxAlarm",
            alarm_name=f"{service_name}-alb-5xx",
            alarm_description="ALB is returning an elevated number of 5xx errors.",
            metric=cw.Metric(
                namespace="AWS/ApplicationELB",
                metric_name="HTTPCode_ELB_5XX_Count",
                dimensions_map={"LoadBalancer": alb_full_name},
                statistic="Sum",
                period=period,
            ),
            threshold=error_5xx_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        alb_5xx.add_alarm_action(alarm_action)
        self._alarms.append(alb_5xx)

        alb_latency = cw.Alarm(
            self,
            "ALBResponseTimeAlarm",
            alarm_name=f"{service_name}-alb-response-time",
            alarm_description="P95 target response time exceeds the SLO.",
            metric=cw.Metric(
                namespace="AWS/ApplicationELB",
                metric_name="TargetResponseTime",
                dimensions_map={"LoadBalancer": alb_full_name},
                statistic="p95",
                period=period,
            ),
            threshold=response_time_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        alb_latency.add_alarm_action(alarm_action)
        self._alarms.append(alb_latency)

        alb_unhealthy = cw.Alarm(
            self,
            "ALBUnhealthyTargetsAlarm",
            alarm_name=f"{service_name}-alb-unhealthy-targets",
            alarm_description="One or more ALB targets are unhealthy.",
            metric=cw.Metric(
                namespace="AWS/ApplicationELB",
                metric_name="UnHealthyHostCount",
                dimensions_map={"LoadBalancer": alb_full_name},
                statistic="Maximum",
                period=period,
            ),
            threshold=0,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        alb_unhealthy.add_alarm_action(alarm_action)
        self._alarms.append(alb_unhealthy)

    # -- ECS alarms ------------------------------------------------------------

    def _create_ecs_alarms(
        self,
        *,
        service_name: str,
        ecs_service: ecs.FargateService,
        alarm_action: cw_actions.SnsAction,
        evaluation_periods: int,
        period: Duration,
        min_healthy_tasks: int,
    ) -> None:
        cluster_name = ecs_service.cluster.cluster_name
        svc_name = ecs_service.service_name

        ecs_tasks = cw.Alarm(
            self,
            "ECSRunningTasksAlarm",
            alarm_name=f"{service_name}-ecs-running-tasks",
            alarm_description=(
                "Running ECS task count has dropped below the minimum, "
                "indicating the service may be unavailable."
            ),
            metric=cw.Metric(
                namespace="AWS/ECS",
                metric_name="RunningTaskCount",
                dimensions_map={
                    "ClusterName": cluster_name,
                    "ServiceName": svc_name,
                },
                statistic="Minimum",
                period=period,
            ),
            threshold=min_healthy_tasks,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.LESS_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.BREACHING,
        )
        ecs_tasks.add_alarm_action(alarm_action)
        self._alarms.append(ecs_tasks)

    # -- RDS alarms ------------------------------------------------------------

    def _create_rds_alarms(
        self,
        *,
        service_name: str,
        rds_instance: rds.IDatabaseInstance,
        alarm_action: cw_actions.SnsAction,
        evaluation_periods: int,
        period: Duration,
        cpu_threshold: float,
        free_storage_threshold_bytes: int,
        connections_threshold: int,
    ) -> None:
        db_id = rds_instance.instance_identifier

        rds_cpu = cw.Alarm(
            self,
            "RDSCPUAlarm",
            alarm_name=f"{service_name}-rds-cpu",
            alarm_description="RDS CPU utilisation is critically high.",
            metric=cw.Metric(
                namespace="AWS/RDS",
                metric_name="CPUUtilization",
                dimensions_map={"DBInstanceIdentifier": db_id},
                statistic="Average",
                period=period,
            ),
            threshold=cpu_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.BREACHING,
        )
        rds_cpu.add_alarm_action(alarm_action)
        self._alarms.append(rds_cpu)

        rds_storage = cw.Alarm(
            self,
            "RDSFreeStorageAlarm",
            alarm_name=f"{service_name}-rds-free-storage",
            alarm_description="RDS free storage is critically low.",
            metric=cw.Metric(
                namespace="AWS/RDS",
                metric_name="FreeStorageSpace",
                dimensions_map={"DBInstanceIdentifier": db_id},
                statistic="Minimum",
                period=period,
            ),
            threshold=free_storage_threshold_bytes,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.LESS_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.BREACHING,
        )
        rds_storage.add_alarm_action(alarm_action)
        self._alarms.append(rds_storage)

        rds_conns = cw.Alarm(
            self,
            "RDSConnectionsAlarm",
            alarm_name=f"{service_name}-rds-connections",
            alarm_description="RDS active connection count is unusually high.",
            metric=cw.Metric(
                namespace="AWS/RDS",
                metric_name="DatabaseConnections",
                dimensions_map={"DBInstanceIdentifier": db_id},
                statistic="Maximum",
                period=period,
            ),
            threshold=connections_threshold,
            evaluation_periods=evaluation_periods,
            comparison_operator=cw.ComparisonOperator.GREATER_THAN_THRESHOLD,
            treat_missing_data=cw.TreatMissingData.NOT_BREACHING,
        )
        rds_conns.add_alarm_action(alarm_action)
        self._alarms.append(rds_conns)
